/**
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

// generated by cdktf get
Object.defineProperty(exports, 'certificate', { get: function () { return require('./certificate'); } });
Object.defineProperty(exports, 'registration', { get: function () { return require('./registration'); } });
Object.defineProperty(exports, 'provider', { get: function () { return require('./provider'); } });

